powershell -Command "Start-Process cmd -ArgumentList '/c cd backend/API && docker-compose up -d'"
powershell -Command "Start-Process cmd -ArgumentList '/c cd backend/monitoring-service/container-status && npm start'"
powershell -Command "Start-Process cmd -ArgumentList '/c cd backend/monitoring-service/endpoint-status && npm start'"
powershell -Command "Start-Process cmd -ArgumentList '/c cd backend/monitoring-service/traffic-status && npm start'"
powershell -Command "Start-Process cmd -ArgumentList '/c cd backend/monitoring-service/system-status && npm start'"
powershell -Command "Start-Process cmd -ArgumentList '/c cd backend/monitoring-service && npm start'"
powershell -Command "Start-Process cmd -ArgumentList '/c cd frontend && npm start'"
